bin/cards checks for venv

diff --git a/bin/cards b/bin/cards
--- a/bin/cards
+++ b/bin/cards
@@ -1,4 +1,9 @@
 #!/bin/zsh
 set -eu -o pipefail
 
+if [[ ! -v VIRTUAL_ENV || ! -d $VIRTUAL_ENV ]]; then
+    echo 'Missing venv.' 1>&2
+    exit 1
+fi
+
 python -m cards $@
